### ISSUE TITLE
Dockerfile for backend and frontend

### ISSUE THREAD

**Issue by edwardh5** [chapter-gtm/chapter#8]
**Describe the bug**
Hi, I'm trying to play with and run this project within a docker container locally, but it appears the Dockerfiles for frontend and backend are missing (perhaps intentional). Would you kindly provide a sample?

**To Reproduce**
1. Clone repo
2. `docker compose up`

**Expected behavior**
I expect the server and frontend to be running, but it appears the docker-compose file specifies the backend and frontend Dockerfile within `./deploy/docker` folder. I think there's 3 Dockerfiles altogether. 

Could you kindly provide a sample? Thanks a ton for this project!

**Comment by shrir** [comment]
@edwardh5 Thanks for catching that. Added the files.

It'll still be a while before I write installation guides but feel free to poke around and reach me for any questions or feedback. By the way, the backend is built on top of [litestar-fullstack](https://github.com/litestar-org/litestar-fullstack), so their docs might help for now.
